# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsParameterBulk < Formula
  desc ""
  homepage "https://github.com/gork74/aws-parameter-bulk"
  version "0.0.13"

  on_macos do
    url "https://github.com/gork74/aws-parameter-bulk/releases/download/v0.0.13/aws-parameter-bulk_0.0.13_darwin_all.tar.gz"
    sha256 "b74fcd3a7ae2c387bed50727cbe91a015400e6e584af4e203fdc3b4edb5ef79d"

    def install
      bin.install "aws-parameter-bulk"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gork74/aws-parameter-bulk/releases/download/v0.0.13/aws-parameter-bulk_0.0.13_linux_amd64.tar.gz"
        sha256 "fc291c6b335fbce6791800e0a3bcfb41c99edbd42a49b31da5e7246add62cad3"

        def install
          bin.install "aws-parameter-bulk"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/gork74/aws-parameter-bulk/releases/download/v0.0.13/aws-parameter-bulk_0.0.13_linux_armv6.tar.gz"
        sha256 "ab97bd1b72774beec7a22242d2f6381af2c3ce15622cfc3b8460f0e73e27552d"

        def install
          bin.install "aws-parameter-bulk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gork74/aws-parameter-bulk/releases/download/v0.0.13/aws-parameter-bulk_0.0.13_linux_arm64.tar.gz"
        sha256 "6d1a88d6f9cdc1893d19871b8a93c969f2685535f10f5f5a0355e323b3d496aa"

        def install
          bin.install "aws-parameter-bulk"
        end
      end
    end
  end
end
