# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsParameterBulk < Formula
  desc ""
  homepage "https://github.com/gork74/aws-parameter-bulk"
  version "0.0.14"

  on_macos do
    url "https://github.com/gork74/aws-parameter-bulk/releases/download/v0.0.14/aws-parameter-bulk_0.0.14_darwin_all.tar.gz"
    sha256 "ee4a30ff894de8371aa39913ff7bb2b843f8a75b267eac9bc4a5d97a74d1846b"

    def install
      bin.install "aws-parameter-bulk"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gork74/aws-parameter-bulk/releases/download/v0.0.14/aws-parameter-bulk_0.0.14_linux_amd64.tar.gz"
        sha256 "674515bed8e8080161fb992658682590bd0aa92f81aef3caa94154e73b924a85"

        def install
          bin.install "aws-parameter-bulk"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/gork74/aws-parameter-bulk/releases/download/v0.0.14/aws-parameter-bulk_0.0.14_linux_armv6.tar.gz"
        sha256 "f5ae96f922959bdc18b30898db2d36523d7b8d0751d985a0c766db83e28f53b0"

        def install
          bin.install "aws-parameter-bulk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gork74/aws-parameter-bulk/releases/download/v0.0.14/aws-parameter-bulk_0.0.14_linux_arm64.tar.gz"
        sha256 "4b72466c6c097851e13feac498448f63f695f81b24e653a413aaf117356fb8d2"

        def install
          bin.install "aws-parameter-bulk"
        end
      end
    end
  end
end
